---
abstract: 'Moose-based XML loader'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  utf8: 1.06
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rabbit
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 2.26
  Moose: 0.88
  MooseX::Role::Parameterized: 0.12
  XML::LibXML: 1.69
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/robinsmidsrod/Rabbit.git
version: 0.01
